# Analise Exploratoria dos Dados Educacionais

# Pandas

In [ ]:
import pandas as pd
base = pd.read_csv("sample_enem.csv")

In [ ]:
base.head()

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,180012177128,2018,M,1,NaN,1,1709302,Guaraí,17,TO,0.0,1.0,1.0,0.0,NaN,463.6,402.4,NaN,340.0
1,180008992256,2018,F,2,1.0,0,2408102,Natal,24,RN,1.0,1.0,1.0,1.0,560.8,628.9,564.7,439.5,600.0
2,180009068293,2018,M,2,1.0,0,2507507,João Pessoa,25,PB,1.0,1.0,1.0,1.0,529.6,650.3,597.0,425.3,700.0
3,180012792933,2018,M,1,1.0,0,2516201,Sousa,25,PB,1.0,1.0,1.0,1.0,404.3,590.5,467.9,413.7,380.0
4,180009062993,2018,M,1,1.0,0,3548906,São Carlos,35,SP,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Tipo de arquivo
type(base)

pandas.core.frame.DataFrame

In [ ]:
# Ultimas linhas
base.tail()

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
5,180008063260,2018,F,2,1.0,0,3523404,Itatiba,35,SP,1.0,1.0,1.0,1.0,571.6,715.0,714.0,691.4,720.0
6,180013610017,2018,F,1,NaN,0,2927408,Salvador,29,BA,1.0,1.0,1.0,1.0,433.7,510.2,514.0,410.4,320.0
7,180009243541,2018,F,1,NaN,0,4106407,Cornélio Procópio,41,PR,1.0,1.0,1.0,1.0,630.0,662.4,682.5,724.1,740.0
8,180009057235,2018,M,1,1.0,0,2933307,Vitória da Conquista,29,BA,1.0,1.0,1.0,1.0,455.7,524.8,535.3,501.7,540.0
9,180007751747,2018,M,1,NaN,0,2604106,Caruaru,26,PE,1.0,1.0,1.0,1.0,565.5,477.2,575.0,721.0,560.0

In [ ]:
# Informacoes
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NU_INSCRICAO        10 non-null     int64
 1   NU_ANO              10 non-null     int64
 2   TP_SEXO             10 non-null     object
 3   TP_ESCOLA           10 non-null     int64
 4   TP_ENSINO           6 non-null      float64
 5   IN_TREINEIRO        10 non-null     int64
 6   CO_MUNICIPIO_PROVA  10 non-null     int64
 7   NO_MUNICIPIO_PROVA  10 non-null     object
 8   CO_UF_PROVA         10 non-null     int64
 9   SG_UF_PROVA         10 non-null     object
 10  TP_PRESENCA_CN      10 non-null     float64
 11  TP_PRESENCA_CH      10 non-null     float64
 12  TP_PRESENCA_LC      10 non-null     float64
 13  TP_PRESENCA_MT      10 non-null     float64
 14  NU_NOTA_CN          8 non-null      float64
 15  NU_NOTA_CH          9 non-null      float64
 16  NU_NOTA_LC          9 non-null      float64
 17  NU_NOTA_MT          8 non-null      float64
 18  NU_NOTA_REDACAO     9 non-null      float64
dtypes: float64(10), int64(6), object(3)
memory usage: 1.6+ KB

In [ ]:
# Tipo de colunas
base.dtypes

NU_INSCRICAO            int64
NU_ANO                  int64
TP_SEXO                object
TP_ESCOLA               int64
TP_ENSINO             float64
IN_TREINEIRO            int64
CO_MUNICIPIO_PROVA      int64
NO_MUNICIPIO_PROVA     object
CO_UF_PROVA             int64
SG_UF_PROVA            object
TP_PRESENCA_CN        float64
TP_PRESENCA_CH        float64
TP_PRESENCA_LC        float64
TP_PRESENCA_MT        float64
NU_NOTA_CN            float64
NU_NOTA_CH            float64
NU_NOTA_LC            float64
NU_NOTA_MT            float64
NU_NOTA_REDACAO       float64
dtype: object

In [ ]:
# Dimensao
base.shape

(10, 19)

In [ ]:
# Colunas
base.columns

Index(['NU_INSCRICAO', 'NU_ANO', 'TP_SEXO', 'TP_ESCOLA', 'TP_ENSINO',
       'IN_TREINEIRO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA',
       'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH',
       'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH',
       'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO'],
      dtype='object')

In [ ]:
# Valores unicos em cada coluna
base.nunique()

NU_INSCRICAO          10
NU_ANO                 1
TP_SEXO                2
TP_ESCOLA              2
TP_ENSINO              1
IN_TREINEIRO           2
CO_MUNICIPIO_PROVA    10
NO_MUNICIPIO_PROVA    10
CO_UF_PROVA            7
SG_UF_PROVA            7
TP_PRESENCA_CN         2
TP_PRESENCA_CH         2
TP_PRESENCA_LC         2
TP_PRESENCA_MT         2
NU_NOTA_CN             8
NU_NOTA_CH             9
NU_NOTA_LC             9
NU_NOTA_MT             8
NU_NOTA_REDACAO        9
dtype: int64

In [ ]:
# Campos vazios
base.isnull().sum()

NU_INSCRICAO          0
NU_ANO                0
TP_SEXO               0
TP_ESCOLA             0
TP_ENSINO             4
IN_TREINEIRO          0
CO_MUNICIPIO_PROVA    0
NO_MUNICIPIO_PROVA    0
CO_UF_PROVA           0
SG_UF_PROVA           0
TP_PRESENCA_CN        0
TP_PRESENCA_CH        0
TP_PRESENCA_LC        0
TP_PRESENCA_MT        0
NU_NOTA_CN            2
NU_NOTA_CH            1
NU_NOTA_LC            1
NU_NOTA_MT            2
NU_NOTA_REDACAO       1
dtype: int64

In [ ]:
# Estatisticas
base.describe()

,NU_INSCRICAO,NU_ANO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,CO_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
count,1.000000e+01,10.0,10.000000,6.0,10.000000,1.000000e+01,10.00000,10.000000,10.000000,10.000000,10.000000,8.000000,9.000000,9.000000,8.000000,9.000000
mean,1.800100e+11,2018.0,1.300000,1.0,0.100000,2.878465e+06,28.60000,0.800000,0.900000,0.900000,0.800000,518.900000,580.322222,561.422222,540.887500,544.444444
std,2.070898e+06,0.0,0.483046,0.0,0.316228,6.920969e+05,6.86699,0.421637,0.316228,0.316228,0.421637,78.874765,89.786730,97.702607,144.933753,164.249133
min,1.800078e+11,2018.0,1.000000,1.0,0.000000,1.709302e+06,17.00000,0.000000,0.000000,0.000000,0.000000,404.300000,463.600000,402.400000,410.400000,320.000000
25%,1.800090e+11,2018.0,1.000000,1.0,0.000000,2.509680e+06,25.00000,1.000000,1.000000,1.000000,1.000000,450.200000,510.200000,514.000000,422.400000,380.000000
50%,1.800091e+11,2018.0,1.000000,1.0,0.000000,2.765757e+06,27.50000,1.000000,1.000000,1.000000,1.000000,545.200000,590.500000,564.700000,470.600000,560.000000
75%,1.800114e+11,2018.0,1.750000,1.0,0.000000,3.375880e+06,33.50000,1.000000,1.000000,1.000000,1.000000,567.025000,650.300000,597.000000,698.800000,700.000000
max,1.800136e+11,2018.0,2.000000,1.0,1.000000,4.106407e+06,41.00000,1.000000,1.000000,1.000000,1.000000,630.000000,715.000000,714.000000,724.100000,740.000000

In [ ]:
# Selecionar Colunas + Estatisticas + Transpor linhas para colunas

base[["NU_NOTA_CN", "NU_NOTA_CH", "NU_NOTA_LC", "NU_NOTA_MT"]].describe().transpose()

            count        mean         std    min    25%    50%      75%    max
NU_NOTA_CN    8.0  518.900000   78.874765  404.3  450.2  545.2  567.025  630.0
NU_NOTA_CH    9.0  580.322222   89.786730  463.6  510.2  590.5  650.300  715.0
NU_NOTA_LC    9.0  561.422222   97.702607  402.4  514.0  564.7  597.000  714.0
NU_NOTA_MT    8.0  540.887500  144.933753  410.4  422.4  470.6  698.800  724.1

In [ ]:
# Ordenar do maior ao menor

base.sort_values("NU_NOTA_MT", ascending=False)

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
7,180009243541,2018,F,1,NaN,0,4106407,Cornélio Procópio,41,PR,1.0,1.0,1.0,1.0,630.0,662.4,682.5,724.1,740.0
9,180007751747,2018,M,1,NaN,0,2604106,Caruaru,26,PE,1.0,1.0,1.0,1.0,565.5,477.2,575.0,721.0,560.0
5,180008063260,2018,F,2,1.0,0,3523404,Itatiba,35,SP,1.0,1.0,1.0,1.0,571.6,715.0,714.0,691.4,720.0
8,180009057235,2018,M,1,1.0,0,2933307,Vitória da Conquista,29,BA,1.0,1.0,1.0,1.0,455.7,524.8,535.3,501.7,540.0
1,180008992256,2018,F,2,1.0,0,2408102,Natal,24,RN,1.0,1.0,1.0,1.0,560.8,628.9,564.7,439.5,600.0
2,180009068293,2018,M,2,1.0,0,2507507,João Pessoa,25,PB,1.0,1.0,1.0,1.0,529.6,650.3,597.0,425.3,700.0
3,180012792933,2018,M,1,1.0,0,2516201,Sousa,25,PB,1.0,1.0,1.0,1.0,404.3,590.5,467.9,413.7,380.0
6,180013610017,2018,F,1,NaN,0,2927408,Salvador,29,BA,1.0,1.0,1.0,1.0,433.7,510.2,514.0,410.4,320.0
0,180012177128,2018,M,1,NaN,1,1709302,Guaraí,17,TO,0.0,1.0,1.0,0.0,NaN,463.6,402.4,NaN,340.0
4,180009062993,2018,M,1,1.0,0,3548906,São Carlos,35,SP,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Contar e Agrupar
base.TP_SEXO.value_counts()

TP_SEXO
M    6
F    4
Name: count, dtype: int64

In [ ]:
base.TP_SEXO.value_counts(normalize=True) * 100

TP_SEXO
M    60.0
F    40.0
Name: proportion, dtype: float64

In [ ]:
# Media
base.NU_NOTA_CN.mean()

518.9

In [ ]:
# Menor Valor
base.NU_NOTA_CN.min()

404.3

In [ ]:
# Maior Valor
base.NU_NOTA_CN.max()

630.0

In [ ]:
# Mediana
base.NU_NOTA_CN.median()

545.2

In [ ]:
# Filtro [Nota de Ciencias Naturais maior que 500]

base.loc[ base.NU_NOTA_CN > 500 ]

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
1,180008992256,2018,F,2,1.0,0,2408102,Natal,24,RN,1.0,1.0,1.0,1.0,560.8,628.9,564.7,439.5,600.0
2,180009068293,2018,M,2,1.0,0,2507507,João Pessoa,25,PB,1.0,1.0,1.0,1.0,529.6,650.3,597.0,425.3,700.0
5,180008063260,2018,F,2,1.0,0,3523404,Itatiba,35,SP,1.0,1.0,1.0,1.0,571.6,715.0,714.0,691.4,720.0
7,180009243541,2018,F,1,NaN,0,4106407,Cornélio Procópio,41,PR,1.0,1.0,1.0,1.0,630.0,662.4,682.5,724.1,740.0
9,180007751747,2018,M,1,NaN,0,2604106,Caruaru,26,PE,1.0,1.0,1.0,1.0,565.5,477.2,575.0,721.0,560.0

In [ ]:
# Filtro [Nota de Ciencias Naturais maior que 500 E Sexo igual a feminino]

base.loc[ (base.NU_NOTA_CN > 500) & ( base.TP_SEXO== "F")]

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
1,180008992256,2018,F,2,1.0,0,2408102,Natal,24,RN,1.0,1.0,1.0,1.0,560.8,628.9,564.7,439.5,600.0
5,180008063260,2018,F,2,1.0,0,3523404,Itatiba,35,SP,1.0,1.0,1.0,1.0,571.6,715.0,714.0,691.4,720.0
7,180009243541,2018,F,1,NaN,0,4106407,Cornélio Procópio,41,PR,1.0,1.0,1.0,1.0,630.0,662.4,682.5,724.1,740.0

In [ ]:
# Filtro [Nota de Ciencias Naturais maior que 500 ou Sexo igual a feminino]

base.loc[ (base.NU_NOTA_CN > 500) | ( base.TP_SEXO== "F")]

,NU_INSCRICAO,NU_ANO,TP_SEXO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
1,180008992256,2018,F,2,1.0,0,2408102,Natal,24,RN,1.0,1.0,1.0,1.0,560.8,628.9,564.7,439.5,600.0
2,180009068293,2018,M,2,1.0,0,2507507,João Pessoa,25,PB,1.0,1.0,1.0,1.0,529.6,650.3,597.0,425.3,700.0
5,180008063260,2018,F,2,1.0,0,3523404,Itatiba,35,SP,1.0,1.0,1.0,1.0,571.6,715.0,714.0,691.4,720.0
6,180013610017,2018,F,1,NaN,0,2927408,Salvador,29,BA,1.0,1.0,1.0,1.0,433.7,510.2,514.0,410.4,320.0
7,180009243541,2018,F,1,NaN,0,4106407,Cornélio Procópio,41,PR,1.0,1.0,1.0,1.0,630.0,662.4,682.5,724.1,740.0
9,180007751747,2018,M,1,NaN,0,2604106,Caruaru,26,PE,1.0,1.0,1.0,1.0,565.5,477.2,575.0,721.0,560.0

In [ ]:
# Agrupando por UF e contar

base.groupby( by=["SG_UF_PROVA"] ).count()["NU_INSCRICAO"]

SG_UF_PROVA
BA    2
PB    2
PE    1
PR    1
RN    1
SP    2
TO    1
Name: NU_INSCRICAO, dtype: int64

# Matplotlib